[package]
name = "oceans-ink"
version = "0.1.0"
edition = "2024"
description = "Unofficial Instapaper client for GNOME"

[dependencies]
gtk = { package = "gtk4", version = "0.10", features = ["v4_18"] }
adw = { package = "libadwaita", version = "0.8", features = ["v1_8"] }
keyring = { version = "3", features = ["async-secret-service", "async-io", "crypto-rust"] }
